GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/675f4b5180df3a2a6aa74c7c

###

DELETE http://localhost:3001/api/persons/679c1535e70d22fa77d78f68

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "alexander chips",
    "number": "7823109845"
}

###

PUT http://localhost:3001/api/persons/alexander chips
Content-Type: application/json

{
    "name": "alexander chips",
    "number": "11111111111"
}