GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/675f4b5180df3a2a6aa74c7c

###

DELETE http://localhost:3001/api/persons/67af84325bac36adcee9bd13

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "great lev",
    "number": "12-456712"
}

###

PUT http://localhost:3001/api/persons/alexander chips
Content-Type: application/json

{
    "name": "alexander chips",
    "number": "12-456712"
}